import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#002e6a",
        "inverse-primary": "#005ac2",
        "outline-variant": "#424754",
        "on-tertiary": "#283044",
        "inverse-on-surface": "#263143",
        "tertiary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#6ffbbe",
        "tertiary-fixed": "#dae2fd",
        "on-surface": "#d8e3fb",
        "surface-container": "#152031",
        "tertiary-container": "#8990a8",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        tertiary: "#bec6e0",
        "surface-container-low": "#111c2d",
        "on-tertiary-container": "#22293d",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-container": "#00311f",
        surface: "#081425",
        outline: "#8c909f",
        "on-background": "#d8e3fb",
        "surface-dim": "#081425",
        "on-primary-fixed": "#001a42",
        "primary-container": "#4d8eff",
        primary: "#adc6ff",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-highest": "#2a3548",
        "surface-bright": "#2f3a4c",
        "surface-container-lowest": "#040e1f",
        "on-error": "#690005",
        "surface-variant": "#2a3548",
        "on-tertiary-fixed": "#131b2e",
        "secondary-container": "#00a572",
        "on-secondary-fixed": "#002113",
        error: "#ffb4ab",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        background: "#081425",
        "on-surface-variant": "#c2c6d6",
        "surface-container-high": "#1f2a3c",
        "inverse-surface": "#d8e3fb",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-secondary": "#003824",
        "surface-tint": "#adc6ff",
        secondary: "#4edea3",
        "on-primary-container": "#00285d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "48px",
        "container-margin": "32px",
        "sidebar-width-expanded": "240px",
        "sidebar-width-collapsed": "64px",
        gutter: "16px",
      },
      fontFamily: {
        geist: ["Geist", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "timer-display": [
          "80px",
          { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
