"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { resetPasswordSchema } from "../../../schemas/authSchemas";
import { authService } from "../../../lib/api/authService";
type Values = { password: string; confirmPassword: string };
function Content() { const token = useSearchParams().get("token"); const [success, setSuccess] = useState(false); const [error, setError] = useState(""); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<Values>({ resolver: zodResolver(resetPasswordSchema) }); const submit = async (values: Values) => { if (!token) { setError("link inválido ou expirado"); return; } try { setError(""); await authService.resetPassword({ token, newPassword: values.password, confirmPassword: values.confirmPassword }); setSuccess(true); } catch { setError("link inválido ou expirado"); } }; return <main className="bg-background min-h-screen flex items-center justify-center"><section className="w-full max-w-md px-6"><div className="bg-surface p-8 rounded-xl"><h1 className="text-primary text-3xl">FocusFlow</h1>{success ? <><h2 className="my-4">Senha redefinida!</h2><p>Sua senha foi atualizada. Faça login para continuar.</p><Link href="/login" className="block mt-6 text-primary">Ir para o login</Link></> : <><h2 className="my-4">Redefina sua senha</h2><form noValidate onSubmit={handleSubmit(submit)}>{([['password','Nova senha'],['confirmPassword','Confirmar senha']] as const).map(([name,label]) => <div className="mb-4" key={name}><label htmlFor={name}>{label}</label><input id={name} type="password" disabled={isSubmitting} aria-invalid={!!errors[name]} aria-describedby={errors[name] ? `${name}-error` : undefined} className="w-full p-3 border rounded" {...register(name)} />{errors[name] && <p id={`${name}-error`} className="text-error">{errors[name]?.message}</p>}</div>)}<p className="text-sm">Senha: 8–15 caracteres, com maiúscula, minúscula, número e caractere especial.</p>{error && <p aria-live="polite" className="text-error">{error}</p>}<button disabled={isSubmitting} className="w-full mt-5 bg-primary p-3 rounded">{isSubmitting ? "Processando..." : "Redefinir senha"}</button></form>{error && <Link href="/forgot-password" className="block mt-5 text-primary">Solicitar novo link</Link>}</>}</div></section></main>; }
export default function ResetPasswordPage() { return <Suspense fallback={<main>Carregando...</main>}><Content /></Suspense>; }
